name: kaffeine-player
version-script: cat Changelog |grep Version|head -1|cut -d' ' -f2
version: "snapshot"
grade: stable
summary: A media player by KDE with digital TV support
confinement: strict
description: |
  Kaffeine is a media player. What makes it different from the others is
  its excellent support of digital TV (DVB). kaffeine-player has user-friendly
  interface, so that even first time users can start immediately playing
  their movies: from DVD (including DVD menus, titles, chapters, etc.),
  VCD, or a file.

apps:
  kaffeine-player:
    desktop: share/applications/org.kde.kaffeine.desktop
    command: desktop-launch $SNAP/bin/kaffeine
    plugs:
      - camera
      - desktop
      - desktop-legacy
      - home
      - mount-observe
      - network
      - network-bind
      - opengl
      - optical-drive
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - unity7
      - x11
    slots:
      - mpris
parts:
  libvlc:
    source: https://github.com/videolan/vlc-3.0.git
    source-tag: 3.0.1
    source-type: git
    plugin: autotools
    prepare: sed -i 's|0\.19\.8|0\.19\.7|'  configure.ac
    build-packages:
      - git
      - g++
      - make
      - yasm
      - autoconf
      - libtool
      - cmake
      - automake
      - build-essential
      - libxcb-xfixes0-dev
      - texinfo
      - libvpx-dev
      - libqt5svg5-dev
      - liba52-0.7.4-dev
      - libaa1-dev
      - libasound2-dev
      - libass-dev
      - libavahi-client-dev
      - libavc1394-dev
      - libbluray-dev
      - libcaca-dev
      - libcairo2-dev
      - libcddb2-dev
      - libcdio-dev
      - libchromaprint-dev
      - try: [libcrystalhd-dev]
      - libdbus-1-dev
      - libdc1394-22-dev
      - libdca-dev
      - libdirectfb-dev
      - libdvbpsi-dev
      - libdvdnav-dev
      - libdvdread-dev
      - libegl1-mesa-dev
      - libfaad-dev
      - libflac-dev
      - libfluidsynth-dev
      - libfreerdp-dev
      - libfreetype6-dev
      - libfribidi-dev
      - libgles2-mesa-dev
      - libgnutls28-dev
      - libgtk2.0-dev
      - libidn11-dev
      - libiso9660-dev
      - libjack-dev
      - libkate-dev
      - liblircclient-dev
      - liblivemedia-dev
      - liblua5.2-dev
      - libmad0-dev
      - libmatroska-dev
      - libmodplug-dev
      - libmpcdec-dev
      - libmpeg2-4-dev
      - libmtp-dev
      - libncursesw5-dev
      - libogg-dev
      - libomxil-bellagio-dev
      - libopus-dev
      - libpng-dev
      - libpostproc-dev
      - try: [libprojectm-dev]
      - libpulse-dev
      - libqt5x11extras5-dev
      - qtbase5-private-dev
      - libraw1394-dev
      - libresid-builder-dev
      - librsvg2-dev
      - libsamplerate0-dev
      - libsdl-image1.2-dev
      - libsdl1.2-dev
      - libsecret-1-dev
      - libshine-dev
      - libshout3-dev
      - libsidplay2-dev
      - libsmbclient-dev
      - libspeex-dev
      - libspeexdsp-dev
      - libssh2-1-dev
      - libswscale-dev
      - libtag1-dev
      - libtheora-dev
      - libtwolame-dev
      - libudev-dev
      - libupnp-dev
      - libv4l-dev
      - libva-dev
      - libvcdinfo-dev
      - libvdpau-dev
      - libvncserver-dev
      - libvorbis-dev
      - libx11-dev
      - libx264-dev
      - libx265-dev
      - libxcb-composite0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-shm0-dev
      - libxcb-xv0-dev
      - libxcb1-dev
      - libxext-dev
      - libxi-dev
      - libxinerama-dev
      - libxml2-dev
      - libxpm-dev
      - libzvbi-dev
      - lua5.2
      - pkg-config
      - qtbase5-dev
      - xz-utils
      - zlib1g-dev
      - bison
      - flex
      - zsh
    stage-packages:
      - fonts-freefont-ttf
      - dbus-x11
      - libaa1
      - libcaca0
      - libcairo2
      - libegl1-mesa
      - libfreerdp-client1.1
      - libfreerdp-core1.1
      - libfreerdp-gdi1.1
      - libfreetype6
      - libfribidi0
      - libgcc1
      - libgl1-mesa-glx
      - libgles2-mesa
      - libglib2.0-0
      - libpulse0
      - libqt5core5a
      - libqt5gui5
      - librsvg2-2
      - libsdl-image1.2
      - libsdl1.2debian
      - libsecret-1-0
      - libva-drm1
      - libva-x11-1
      - libva1
      - libvdpau1
      - libvncclient1
      - libx11-6
      - libxcb-composite0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-shm0
      - libxcb-xv0
      - libxcb1
      - libxext6
      - libxi6
      - libxinerama1
      - libxpm4
      - vdpau-va-driver
      - i965-va-driver
      - mesa-utils
      - mesa-vdpau-drivers
      - zlib1g
      - try: [libprojectm2v5]
      - projectm-data
      - kde-style-breeze
      - breeze-icon-theme
      - frameworkintegration
      - try: [plasma-integration]
      - phonon4qt5-backend-null
    filesets:
      exclusion:
      - "-usr/lib/*/cmake/*"
      - "-usr/include/*"
      - "-usr/share/ECM/*"
      - "-usr/share/doc/*"
      - "-usr/share/man/*"
      - "-usr/share/icons/breeze-dark*"
      - "-usr/bin/X11"
      - "-usr/bin"
      - "-usr/lib/gcc/x86_64-linux-gnu/6.0.0"
      - "-usr/lib/aspell/*"
    prime:
      - "$exclusion"

  kaffeine-player:
    source: .
    source-type: git
    plugin: cmake
    after:
      - desktop-qt5
      - libvlc
    build-packages:
      - cmake
      - extra-cmake-modules
      - g++
      - gettext
      - kdelibs5-dev
      - kio-dev
      - libdvbv5-dev
      - libkf5coreaddons-dev
      - libkf5i18n-dev
      - libkf5solid-dev
      - libkf5widgetsaddons-dev
      - libkf5windowsystem-dev
      - libqt5x11extras5-dev
      - libxss-dev
      - make
      - qt5-default
