name: kaffeine-player
version-script: cat Changelog |grep Version|head -1|cut -d' ' -f2
version: "snapshot"
summary: A media player by KDE with digital TV support
confinement: devmode
grade: devel
description: |
  Kaffeine is a media player. What makes it different from the others is
  its excellent support of digital TV (DVB). kaffeine-player has user-friendly
  interface, so that even first time users can start immediately playing
  their movies: from DVD (including DVD menus, titles, chapters, etc.),
  VCD, or a file.

apps:
  kaffeine-player:
    desktop: share/applications/org.kde.kaffeine.desktop
    command: bin/desktop-launch kaffeine
    plugs:
      - camera
      - desktop
      - desktop-legacy
      - home
      - mount-observe
      - network
      - network-bind
      - opengl
      - optical-drive
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - unity7
      - x11
    slots:
      - mpris
parts:
  kaffeine-player:
    source: .
    source-type: git
    plugin: cmake
    after: [desktop-qt5]
    build-packages:
      - cmake
      - extra-cmake-modules
      - g++
      - gettext
      - kdelibs5-dev
      - kio-dev
      - libdvbv5-dev
      - libkf5coreaddons-dev
      - libkf5i18n-dev
      - libkf5solid-dev
      - libkf5widgetsaddons-dev
      - libkf5windowsystem-dev
      - libqt5x11extras5-dev
      - libvlc-dev
      - libxss-dev
      - make
      - qt5-default

  desktop-qt5:
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
      - libc6
      - zlib1g
      - locales-all


  gnu-bash:
    source: http://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz
    plugin: autotools
    configflags: ["--infodir=/var/bash/info"]
